from fpdf import FPDF
from datetime import datetime


class FlintlockReport(FPDF):
    def header(self):
        self.set_fill_color(26, 26, 46)
        self.rect(0, 0, 210, 30, 'F')
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 16)
        self.set_xy(10, 8)
        self.cell(0, 10, "Flintlock - Firewall Security Report")
        self.set_font("Helvetica", "", 9)
        self.set_xy(10, 20)
        self.cell(0, 5, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Generated by Flintlock v1.0", align="C")


def draw_summary_boxes(pdf, counts):
    """Draw summary boxes in a straight horizontal line"""
    box_width = 55
    box_height = 22
    start_y = pdf.get_y()
    positions = [10, 75, 140]

    styles = [
        ((255, 229, 229), (255, 68, 68), (200, 0, 0)),
        ((255, 248, 229), (255, 170, 0), (160, 100, 0)),
        ((229, 240, 255), (68, 136, 255), (0, 80, 200)),
    ]
    labels = ["High Severity", "Medium Severity", "Total Issues"]

    for i, (x, (fill, draw, text)) in enumerate(zip(positions, styles)):
        pdf.set_fill_color(*fill)
        pdf.set_draw_color(*draw)
        pdf.rect(x, start_y, box_width, box_height, 'FD')

        pdf.set_text_color(*text)
        pdf.set_font("Helvetica", "B", 20)
        pdf.set_xy(x, start_y + 3)
        pdf.cell(box_width, 10, str(counts[i]), align="C")

        pdf.set_font("Helvetica", "", 9)
        pdf.set_xy(x, start_y + 14)
        pdf.cell(box_width, 6, labels[i], align="C")

    pdf.set_xy(10, start_y + box_height + 5)


def draw_findings_section(pdf, title, findings, fill_color, draw_color, text_color):
    if not findings:
        return

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(26, 26, 46)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 8, f"  {title}", ln=True, fill=True)
    pdf.ln(2)

    for finding in findings:
        pdf.set_fill_color(*fill_color)
        pdf.set_draw_color(*draw_color)
        pdf.set_text_color(*text_color)
        pdf.set_font("Helvetica", "", 8)
        pdf.multi_cell(0, 7, finding, border=1, fill=True)
        pdf.ln(1)

    pdf.ln(4)


def generate_report(findings, filename, vendor, compliance=None, output_path="report.pdf"):
    # Categorize findings
    high = [f for f in findings if "[HIGH]" in f and not any(x in f for x in ["PCI-", "CIS-", "NIST-"])]
    medium = [f for f in findings if "[MEDIUM]" in f and not any(x in f for x in ["PCI-", "CIS-", "NIST-"])]
    pci_high = [f for f in findings if "PCI-HIGH" in f]
    pci_medium = [f for f in findings if "PCI-MEDIUM" in f]
    cis_high = [f for f in findings if "CIS-HIGH" in f]
    cis_medium = [f for f in findings if "CIS-MEDIUM" in f]
    nist_high = [f for f in findings if "NIST-HIGH" in f]
    nist_medium = [f for f in findings if "NIST-MEDIUM" in f]

    total_high = len(high) + len(pci_high) + len(cis_high) + len(nist_high)
    total_medium = len(medium) + len(pci_medium) + len(cis_medium) + len(nist_medium)

    pdf = FlintlockReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Meta info
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 6, f"File: {filename}   |   Vendor: {vendor.upper()}   |   Framework: {compliance.upper() if compliance else 'None'}")
    pdf.ln(10)

    # Summary boxes - all on same Y line
    draw_summary_boxes(pdf, [total_high, total_medium, len(findings)])
    pdf.ln(5)

    # Findings grouped by category
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(26, 26, 46)
    pdf.cell(0, 8, "Findings")
    pdf.ln(8)

    draw_findings_section(pdf, "High Severity", high,
        (255, 229, 229), (255, 68, 68), (180, 0, 0))

    draw_findings_section(pdf, "Medium Severity", medium,
        (255, 248, 229), (255, 170, 0), (160, 100, 0))

    if pci_high or pci_medium:
        draw_findings_section(pdf, "PCI Compliance - High", pci_high,
            (255, 229, 229), (255, 68, 68), (180, 0, 0))
        draw_findings_section(pdf, "PCI Compliance - Medium", pci_medium,
            (255, 248, 229), (255, 170, 0), (160, 100, 0))

    if cis_high or cis_medium:
        draw_findings_section(pdf, "CIS Compliance - High", cis_high,
            (255, 229, 229), (255, 68, 68), (180, 0, 0))
        draw_findings_section(pdf, "CIS Compliance - Medium", cis_medium,
            (255, 248, 229), (255, 170, 0), (160, 100, 0))

    if nist_high or nist_medium:
        draw_findings_section(pdf, "NIST Compliance - High", nist_high,
            (255, 229, 229), (255, 68, 68), (180, 0, 0))
        draw_findings_section(pdf, "NIST Compliance - Medium", nist_medium,
            (255, 248, 229), (255, 170, 0), (160, 100, 0))

    pdf.output(output_path)
    return output_path